### ISSUE TITLE
Include a SynchronousResponder as the first responder in the Responder chain

### ISSUE THREAD

**Issue by tsldevteam** [TechnologySolutionsUkLtd/ascii-protocol#1]
The addition of the _SynchronousResponder_ in the _Responder_ chain was originally provided to allow developers to choose where in the chain synchronous commands are handled. This implementation of _AsciiCommander_'s handling of synchronous commands will ensure that only responses from the originating command are waited for - other responses to similar commands will be passed along the chain. So, the location of the SynchronousResponder in the chain no longer matters. Note: in some of the Native SDKs synchronous commands will consume the first response of the correct type even though it may not be from the originating command.

By adding the _SynchronousResponder_ by default the _AsciiCommander_ interface and the _AddResponder()_ method can be simplified - this will also avoid a common developer error of failing to add the _SynchronousResponder_ and then trying to execute a Synchronous command.

**Comment by tsldevteam** [comment]
If this were implemented as described then the LoggerResponder would no longer log synchronous commands. To get around this problem we could make the LoggerResponder a switchable option on the AsciiCommander.

**Comment by robinTsl** [comment]
We'll leave the API as is
