### ISSUE TITLE
Compatibility - MAUI, Windows 11

### ISSUE THREAD

**Issue by Gogzs** [TechnologySolutionsUkLtd/ascii-protocol#10]
We're currently evaluating MAUI for our client development to target iOS, Android and Windows.
Currently we use WPF to build our desktop app, and Xamarin.Forms for iOS and Android and everything works fine.
With MAUI, we're running into the following issue. When we try to invoke something like:

`var readerLIst = await ReaderManager.ListAvailableReadersAsync(); // Reader manager is an instance of ReaderConnectionManager`

We get the following error: System.PlatformNotSupportedException: 'Please reference the platform specific version of this dll for your target in your project'

I hope it's something silly, since you seem to be supporting everything needed to run on Windows this way. Shame the whole project isn't on github as an OSS project, would be glad to offer my help to get this working.

Thanks in advance!

**Comment by robinTsl** [comment]
Hello,

Please email [support@tsl.com](mailto:support@tsl.com) for the complete answer but in summary; The current nuget package relies on a nuget bait and switch method to select the correct platform specific package depending on what the target the application is built for. As .NET Core / MAUI is multi-platform the .NET Standard implementation is selected which does not know how to connect to a specific platform. We are working on a update to support .NET Core / MAUI but in the meantime the workaround is to download the nuget package and manually reference the dlls for the target you are building for. When the update is available you should be able to revert to the latest nuget package.

**Comment by Gogzs** [comment]
Hey, thanks for the quick update. I thought it would be something like that. Manually added the dll references for the windows target, works as intended. Cheers!

**Comment by Gogzs** [comment]
Just to bump this a little, any news on an update for the packages to support .NET Core/MAUI properly now that MAUI is in RC stage?

**Comment by pvanroos** [comment]
@robinTsl Hi! We have purchased the 1128 with the goal of using it with .NET MAUI also.  What is the status of this?

**Comment by Gogzs** [comment]
@pvanroos I mean, you can still use it if you reference for each platform it's DLL... we're slowly wrapping up the V1 of our app, and we'd like to be able to refference just one nuget package, instead of having the DLLs in the solution and subsequently the DLLs ending up on our git repo... it's just convenience, otherwise it works :)

**Comment by pvanroos** [comment]
@Gogzs Oh, I get it now.  Ok.  I have an existing Xamarin Forms solution in production that we plan on migrating to .NET MAUI so I'm looking forward to this update.

**Comment by robinTsl** [comment]
Please use TSL.AsciiProtocol (preview) for .NET 8 and MAUI
