### ISSUE TITLE
Work around for Android 13

### ISSUE THREAD

**Issue by tony683** [TechnologySolutionsUkLtd/ascii-protocol#12]
HI,

I am using TSL ascii protocol library to read RFIDs.
As far it is working perfectly in all android devices ,
But in Android 13 it is not working,Its throwing error-
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE

Being a developer ,I know about this issue,but to fix it will be needing source code 
to edit it or is there any workaround??

Platform-Xamarin

**Comment by robinTsl** [comment]
Hello, 

You should be able to update to the latest [Xamarin nuget](https://www.nuget.org/packages/Tsl.AsciiProtocol.Std/1.6.0#release-body-tab) and make a couple of minor changes to support the latest Android.
[Xamarin Update News](https://www.tsl.com/new-release-of-the-tsl-ascii-2-software-development-kit-for-xamarin-net-standard-development/)

**Comment by tony683** [comment]
Thanks a lot,It worked...I just had to add bluetooth permission codes
