### ISSUE TITLE
Bug: v0.9.3: UWP ListAvailableReadersAsync() fails under W10 Anniversary Ed (1607)

### ISSUE THREAD

**Issue by andyTSL** [TechnologySolutionsUkLtd/ascii-protocol#5]
1) Format of data returned by DeviceInformation.FindAllAsync has changed (BT address) and friendly-name look up is returning "Bluetooth Serial Port".

2) LINQ call needs to be FirstOrDefault rather than First to prevent exception.

**Comment by robinTsl** [comment]
Fixed in release 0.9.4
