### ISSUE TITLE
ListAvailableReadersAsync()  detects DISCONNECTED Reader

### ISSUE THREAD

**Issue by weirdyang** [TechnologySolutionsUkLtd/ascii-protocol#7]
Hello,
I am having an issue where ListAvailableReadersAsync()  falsely detects a reader that was previously connected via USB. How do I resolve this?

Also, it doesn't seem to list any of the Bluetooth connected readers on COM4 and COM3, how do I get it to pick those up?

**Comment by robinTsl** [comment]
This sounds like an issue from the desktop target? If you use the include pre-release for your nuget packages you should find a 1.2 beta 1 that address these issues.

**Comment by weirdyang** [comment]
Thank you I will try that tomorrow when I get into the office.

In the meanwhile, do you have any sample applications for wpf ? I’m having
trouble getting the .NET examples to work.


I’m currently working with a client who is looking to integrate TSL rfid
readers into their workflow. I have been using the Xamarin examples to
explore the functions and trying to build a sample WPF app and class
library in VB.Net. I’ve read the documentation and trying to decide if it
will be easier to use the ascii wedge. Any help will be greatly appreciated.

Thanks again.

**Comment by robinTsl** [comment]
Would you be able to email support [at] tsl.com? that is the preferred channel for developer support. The console projects in the Xamarin solutions show the basic setup to get an AsciiCommander working. We may have some VB samples for the previous .NET Desktop SDK which uses the same API

**Comment by robinTsl** [comment]
Just to answer this here also. Prior to 1.2 the desktop ReaderConnectionManager listed just the previously installed USB COM ports whether they were currently connected to the computer or not. A connection could be made to any COM port using:

`commander.Transport = new TechnologySolutions.Rfid.AsciiProtocol.Extensions.AsciiSerialTransport("COM7");`

and hence bypass the ReaderConnectionManager. UWP, Android and iOS use Bluetooth APIs so can connect directly to a Bluetooth device. It was only the desktop platform that had this limitation. From 1.2 onwards the desktop API lists the present com  ports for both USB and Bluetooth for connection so the connection can be made using the ReaderConnectionManager.

**Comment by weirdyang** [comment]
Hello Robin,

I've updated my nuget package to the prelease 1.2, however it is still
detecting the disconnected reader. I will try to connect directly to the
COM port and bypass the ReaderConnectionManager.
Please see the attached picture for the issue and the reader serial number.

[image: image.png]

Thanks again and best regards,
Weiyang

**Comment by weirdyang** [comment]
Hello Robin,

I've tried bypassing the ReaderConnectionManager as you have suggested,
however I am now getting this error:

[image: image.png]

Best Regards,
Weiyang
