### ISSUE TITLE
compatibility .net core 3.1

### ISSUE THREAD

**Issue by joshhostetler96** [TechnologySolutionsUkLtd/ascii-protocol#9]
I am not able to get any bluetooth or Usb transports to appear in my .net core 3.1 wpf application.  The only transport I see is Physical = Unknown.

**Comment by robinTsl** [comment]
While the vast majority of the code is platform independent the connection to the reader via Bluetooth or USB requires platform specific APIs. Which platform(s) do you intend to run your application on?

**Comment by joshhostetler96** [comment]
We run on Windows 10 64 bit

**Comment by robinTsl** [comment]
We have published a preview of Tsl.AsciiProtocol for .NET 8 and MAUI
